application: performance-presentation
version: 1
runtime: go
api_version: go1
handlers:

- url: /css/
  static_dir: css

- url: /js 
  static_dir: js
  
- url: /plugin
  static_dir: plugin

- url: /lib
  static_dir: lib

- url: /images
  static_dir: images
  
- url: /.*
  script: _go_app

skip_files:
- ^node_modules$
